### ISSUE TITLE
[request] modrinth release 

### ISSUE THREAD

**Issue by Yarden-zamir** [jaredlll08/no-shade#1]
I know this is like, bearly just got out of the over but can we haz modrinth?

**Comment by jaredlll08** [comment]
The mod is already on modrinth, just under review
![image](https://github.com/jaredlll08/no-shade/assets/5553605/59733a92-ee7c-4a84-a181-4dc3379fc286)

I submitted both mods at the same time, however CurseForge was just quicker reviewing it.

**Comment by Yarden-zamir** [comment]
Ah awesome. Thanks 😅
